version: '3.8'

services:
  nftruth-api:
    build: .
    container_name: nftruth-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENSEA_API_KEY=${OPENSEA_API_KEY:-}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID:-}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET:-}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT:-NFTruth/1.0}
    volumes:
      # Mount model outputs to persist data
      - ./model_outputs:/app/model_outputs:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nftruth-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: nftruth-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nftruth-api
    restart: unless-stopped
    networks:
      - nftruth-network
    profiles:
      - production

networks:
  nftruth-network:
    driver: bridge

volumes:
  model_data:
    driver: local