apiVersion: v1
kind: ConfigMap
metadata:
  name: nftruth-config
  namespace: nftruth
data:
  # Application configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8000"
  HOST: "0.0.0.0"
