COLLECTION_SLUGS = {
    "Pudgy Penguins": "pudgypenguins",
    "Bored Ape Yacht Club": "boredapeyachtclub",
    "Mutant Ape Yacht Club": "mutant-ape-yacht-club",
    "CryptoPunks": "cryptopunks",
    "Azuki": "azuki",
    "Doodles": "doodles-official",
    "CloneX": "clone-x-x-takashi-murakami",
    "Cool Cats": "cool-cats-nft",
    "Otherdeed": "otherdeed",
    "Moonbirds": "moonbirds",
    "World of Women": "world-of-women-nft",
    "Meebits": "meebits",
    "DeGods": "degods",
    "y00ts": "y00ts",
    "Milady Maker": "milady",
    "Infinex Patrons": "infinexpatrons",
    "Chromie Squiggle": "chromie-squiggle",
    "Autoglyphs": "autoglyphs",
    "Lil Pudgys": "lilpudgys",
    "Fidenza": "fidenza",
    "Runestone": "runestone",
    "Bitcoin Puppets": "bitcoin-puppets",
    "Mad Lads": "mad-lads",
    "Sappy Seals": "sappy-seals",
    "Kanpai Pandas": "kanpai-pandas",
    "Nakamigos": "nakamigos",
    "ON1 Force": "on1-force",
    "Bored Ape Kennel Club": "bored-ape-kennel-club",
    "HV-MTL": "hv-mtl",
    "10KTF": "10ktf",
    "Invisible Friends": "invisiblefriends",
    "BEANZ": "beanzofficial",
    "Deadfellaz": "deadfellaz",
    "Pixelmon": "pixelmon-genesis",
    "Seizon": "seizon",
    "KILLABEARS": "killabears",
    "Quirkies": "quirkies",
    "Loot": "lootproject",
    "Rektguy": "rektguy",
    "Checks": "checks-vv-originals",
    "Renga": "renga",
    "VeeFriends": "veefriends",
    "The Sandbox": "sandbox",
    "Axie Infinity": "axie-infinity",
    "BAYC Mutant Serum": "mutant-serum",
    "CryptoKitties": "cryptokitties",
    "NBA Top Shot": "nba-top-shot",
}