COLLECTION_SLUGS = {
    "Pudgy Penguins": "pudgypenguins",
    "Bored Ape Yacht Club (BAYC)": "boredapeyachtclub",
    "Mutant Ape Yacht Club": "mutant-ape-yacht-club",
    "CryptoPunks": "cryptopunks",
    "Azuki": "azuki",
    "Doodles": "doodles-official",
    "CloneX": "clonex",
    "Cool Cats": "cool-cats-nft",
    "Otherdeed": "otherdeed",
    "Moonbirds": "proof-moonbirds",
    "World of Women": "world-of-women-nft",
    "Meebits": "meebits",
    "DeGods": "degods-eth",
    "y00ts": "y00ts-polygon",
    "Milady Maker": "milady",
    "Infinex Patrons": "infinex-patrons",
    "Chromie Squiggle": "chromie-squiggle-by-snowfro",
    "Autoglyphs": "autoglyphs",
    "Lil Pudgys": "lilpudgys",
    "Fidenza": "fidenza-by-tyler-hobbs",
    "Runestone": "rune-stones-by-fehuart",
    "Mad Lads": "mad-lads-on-polygon",
    "Sappy Seals": "sappy-seals",
    "Kanpai Pandas": "kanpai-pandas",
    "Nakamigos": "nakamigos",
    "ON1 Force": "0n1-force",
    "Bored Ape Kennel Club": "bored-ape-kennel-club",
    "HV-MTL": "hv-mtl",
    "10KTF": "10ktf",
    "Invisible Friends": "invisiblefriends",
    "BEANZ": "beanzofficial",
    "Deadfellaz": "deadfellaz",
    "Pixelmon": "pixelmongen1",
    "Seizon": "seizonofficial",
    "KILLABEARS": "killabears",
    "Quirkies": "quirkiesoriginals",
    "Loot": "lootproject",
    "Rektguy": "rektguy",
    "Checks": "vv-checks-originals",
    "Renga": "renga",
    "VeeFriends": "veefriends",
    "The Sandbox": "sandbox",
    "Axie Infinity": "axie-infinity",
    "Axie": "axie-ronin",
    "CryptoKitties": "cryptokitties",
    "NBA Top Shot": "nba-top-shot",
}